version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: zlagoda_postgres
    restart: always
    environment:
      POSTGRES_USER: zlagoda_user
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: zlagoda_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: