"""Add category, customer and product

Revision ID: 3a12b60d0693
Revises: 8692a00cd7c5
Create Date: 2026-04-15 21:54:21.195085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a12b60d0693'
down_revision: Union[str, Sequence[str], None] = '8692a00cd7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_number', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('category_number')
    )
    op.create_table('customer_card',
    sa.Column('card_number', sa.String(length=13), nullable=False),
    sa.Column('cust_surname', sa.String(length=50), nullable=False),
    sa.Column('cust_name', sa.String(length=50), nullable=False),
    sa.Column('cust_patronymic', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=13), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=9), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('card_number')
    )
    op.create_table('product',
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('category_number', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=50), nullable=False),
    sa.Column('characteristics', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['category_number'], ['category.category_number'], onupdate='CASCADE', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id_product')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('customer_card')
    op.drop_table('category')
    # ### end Alembic commands ###
