"""Init Employee

Revision ID: 8692a00cd7c5
Revises: 
Create Date: 2026-04-15 18:31:56.391040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8692a00cd7c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id_employee', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('empl_surname', sa.String(length=50), nullable=False),
    sa.Column('empl_name', sa.String(length=50), nullable=False),
    sa.Column('empl_patronymic', sa.String(length=50), nullable=True),
    sa.Column('empl_role', sa.String(length=10), nullable=False),
    sa.Column('salary', sa.Numeric(precision=13, scale=4), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('date_of_start', sa.Date(), nullable=False),
    sa.Column('phone_number', sa.String(length=13), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('street', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id_employee')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
