"""Add store_product, check and sale

Revision ID: 91204d7255f6
Revises: 3a12b60d0693
Create Date: 2026-04-15 22:08:42.254533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91204d7255f6'
down_revision: Union[str, Sequence[str], None] = '3a12b60d0693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check',
    sa.Column('check_number', sa.String(length=10), nullable=False),
    sa.Column('id_employee', sa.String(length=10), nullable=False),
    sa.Column('card_number', sa.String(length=13), nullable=True),
    sa.Column('print_date', sa.DateTime(), nullable=False),
    sa.Column('sum_total', sa.Numeric(precision=13, scale=4), nullable=False),
    sa.Column('vat', sa.Numeric(precision=13, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['card_number'], ['customer_card.card_number'], onupdate='CASCADE', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['id_employee'], ['employee.id_employee'], onupdate='CASCADE', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('check_number')
    )
    op.create_table('store_product',
    sa.Column('UPC', sa.String(length=12), nullable=False),
    sa.Column('UPC_prom', sa.String(length=12), nullable=True),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=13, scale=4), nullable=False),
    sa.Column('products_number', sa.Integer(), nullable=False),
    sa.Column('promotional_product', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['UPC_prom'], ['store_product.UPC'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_product'], ['product.id_product'], onupdate='CASCADE', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('UPC')
    )
    op.create_table('sale',
    sa.Column('UPC', sa.String(length=12), nullable=False),
    sa.Column('check_number', sa.String(length=10), nullable=False),
    sa.Column('product_number', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=13, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['UPC'], ['store_product.UPC'], onupdate='CASCADE', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['check_number'], ['check.check_number'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('UPC', 'check_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    op.drop_table('store_product')
    op.drop_table('check')
    # ### end Alembic commands ###
