"""Add search indexes

Revision ID: a7b86a8c20ff
Revises: c92974dc15be
Create Date: 2026-04-17 11:47:14.273272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b86a8c20ff'
down_revision: Union[str, Sequence[str], None] = 'c92974dc15be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_category_category_name'), 'category', ['category_name'], unique=False)
    op.create_index(op.f('ix_customer_card_cust_surname'), 'customer_card', ['cust_surname'], unique=False)
    op.create_index(op.f('ix_employee_empl_surname'), 'employee', ['empl_surname'], unique=False)
    op.create_index(op.f('ix_product_product_name'), 'product', ['product_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_product_name'), table_name='product')
    op.drop_index(op.f('ix_employee_empl_surname'), table_name='employee')
    op.drop_index(op.f('ix_customer_card_cust_surname'), table_name='customer_card')
    op.drop_index(op.f('ix_category_category_name'), table_name='category')
    # ### end Alembic commands ###
